// Code generated by "stringer -type TaskStatus ./handle_storage.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TODO-0]
	_ = x[InProgress-1]
	_ = x[Done-2]
}

const _TaskStatus_name = "TODOInProgressDone"

var _TaskStatus_index = [...]uint8{0, 4, 14, 18}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
